#ifndef LIBAPRS_VERSION_H
#define LIBAPRS_VERSION_H

#define LIBAPRS_VERSION_MAJOR 0
#define LIBAPRS_VERSION_MINOR 1
#define LIBAPRS_VERSION_PATCH 0

#define LIBAPRS_VERSION_STRING "0.1.0"

#endif /* LIBAPRS_VERSION_H */
