#ifndef LIBAPRS_VERSION_H
#define LIBAPRS_VERSION_H

#define LIBAPRS_VERSION_MAJOR 1
#define LIBAPRS_VERSION_MINOR 0
#define LIBAPRS_VERSION_PATCH 1

#define LIBAPRS_VERSION_STRING "1.0.1"

#endif /* LIBAPRS_VERSION_H */
