#ifndef LIBAPRS_VERSION_H
#define LIBAPRS_VERSION_H

#define LIBAPRS_VERSION_MAJOR 1
#define LIBAPRS_VERSION_MINOR 0
#define LIBAPRS_VERSION_PATCH 2

#ifdef LIBAPRS_GIT_HASH
#define LIBAPRS_VERSION_STRING "1.0.2+" LIBAPRS_GIT_HASH
#else
#define LIBAPRS_VERSION_STRING "1.0.2"
#endif

#endif /* LIBAPRS_VERSION_H */
